import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import BaseProvider from "@/components/Provider/BaseProvider";

export const metadata: Metadata = {
  title: "Art Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <BaseProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </BaseProvider>
      </body>
    </html>
  );
}
